/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "3649926a0bb43e258427a6d50c174fcaa4e339ae"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
