executable("views_smoke") {
  testonly = true
  sources = [ "views_smoke_main.cc" ]
  deps = [
    "//base",
    "//base/test:test_support",
    "//components/viz/host",
    "//components/viz/service",
    "//mojo/core/embedder",
    "//third_party/perfetto/src/trace_processor:export_json",
    "//third_party/perfetto/src/trace_processor:storage_minimal",
    "//ui/aura",
    "//ui/base",
    "//ui/base/ime",
    "//ui/compositor",
    "//ui/compositor:test_support",
    "//ui/gfx",
    "//ui/gl",
    "//ui/resources:ui_test_pak",
    "//ui/views",
    "//ui/views:test_support",
    "//ui/wm",
  ]
  if (is_win) {
    deps += [ "//build/win:default_exe_manifest" ]
  }
}
