/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_WEBGPU_DAWN_COMMIT_HASH_H_
#define GPU_WEBGPU_DAWN_COMMIT_HASH_H_

#define DAWN_COMMIT_HASH "3e6e57a3eeda2e7756dc0f41ba44e7bb30fbafc5"

#endif  // GPU_WEBGPU_DAWN_COMMIT_HASH_H_
