/* Generated by lastchange.py, do not edit.*/

#ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_
#define SKIA_EXT_SKIA_COMMIT_HASH_H_

#define SKIA_COMMIT_HASH "30ad01017a46a31859b580bc907457b0e43907a8"

#endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_
